[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]] # Color Scheme
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
'''

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]] # ステータスバーのカラー設定
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
	    \ 'component': {
	    \   'readonly': '%{&readonly?"":""}',
	    \ },
	    \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2"},
	    \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" },
	    \ }
	set laststatus=2
	set noshowmode
'''

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # markdown
repo = 'kannokanno/previm'
hook_add = '''
	let g:previm_open_cmd = 'open -a "Google Chrome"'
'''
