[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]] # Color Scheme
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
'''

[[plugins]] # ステータスバーのカラー設定
repo = 'itchyny/lightline.vim'
hook_add = '''
	set laststatus=2
	set noshowmode
'''

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'
