[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'
hook_add = '''
    autocmd FileType python map <buffer> <F3> :call Flake8()<CR> " キーバインド変更
    let g:flake8_quickfix_location="topleft" " Quickfixの位置
    let g:flake8_quickfix_height=7 " Quickfixの高さ
    let g:flake8_show_in_gutter=1  " 左端にシンボルを表示
    let g:flake8_show_in_file=1  " ファイル内にマークを表示
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
     let g:jedi#completions_command = "<C-N>"
'''

[[plugins]]
repo = 'tsuyoshiwada/slack-memo-vim'
depends = ['webapi-vim']
hook_add = '''
    if filereadable(expand('~/.vimrc.local'))
      source ~/.vimrc.local
    endif
'''

[[plugins]]
repo = 'lambdalisue/vim-gita'
